Repository karmada-io/kubernetes, pull requests merged in 2023-12, with the labels that each got.

#1 Add resource routing logic to fleet-apiserver
  cmd/kube-apiserver/app/aggregator.go
  cmd/kube-apiserver/app/config.go
  cmd/kube-apiserver/app/options/completion.go
  cmd/kube-apiserver/app/server.go
  pkg/controlplane/apiserver/apiextensions.go
  pkg/controlplane/apiserver/config.go
  pkg/controlplane/instance.go
  pkg/controlplane/instance_test.go
  pkg/registry/apps/deployment/storage/storage.go
  pkg/registry/core/namespace/storage/storage.go
  pkg/registry/flowcontrol/rest/storage_flowcontrol.go
  pkg/registry/networking/ingress/storage/decorator.go
  pkg/registry/networking/ingress/storage/storage.go
  staging/src/k8s.io/apiextensions-apiserver/pkg/cmd/server/options/options.go
  staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/etcd.go
  staging/src/k8s.io/apiextensions-apiserver/test/integration/conversion/conversion_test.go
  staging/src/k8s.io/apiextensions-apiserver/test/integration/defaulting_test.go
  staging/src/k8s.io/apiextensions-apiserver/test/integration/fixtures/server.go
  staging/src/k8s.io/apiextensions-apiserver/test/integration/objectmeta_test.go
  staging/src/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/create.go
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/delete.go
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/patch.go
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/update.go
  staging/src/k8s.io/apiserver/pkg/endpoints/installer.go
  staging/src/k8s.io/apiserver/pkg/endpoints/request/context.go
  staging/src/k8s.io/apiserver/pkg/endpoints/request/requestinfo.go
  staging/src/k8s.io/apiserver/pkg/registry/generic/options.go
  staging/src/k8s.io/apiserver/pkg/registry/generic/registry/error.go
  staging/src/k8s.io/apiserver/pkg/registry/generic/registry/fleet.go
  staging/src/k8s.io/apiserver/pkg/registry/generic/registry/mcrv.go
  staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go
  staging/src/k8s.io/apiserver/pkg/registry/generic/registry/utils.go
  staging/src/k8s.io/apiserver/pkg/registry/rest/update.go
  staging/src/k8s.io/apiserver/pkg/server/config.go
  staging/src/k8s.io/apiserver/pkg/server/options/etcd.go
  staging/src/k8s.io/apiserver/pkg/server/options/serving.go
  staging/src/k8s.io/apiserver/pkg/server/options/serving_with_loopback.go
  staging/src/k8s.io/apiserver/pkg/storage/interfaces.go
  staging/src/k8s.io/apiserver/pkg/util/webhook/webhook.go
  test/integration/controlplane/transformation/kmsv2_transformation_test.go
Labels: lgtm, size/XXL, approved

#3 add support for CRD, pods/log and pods/exec
  cmd/kube-apiserver/app/aggregator.go
  pkg/controlplane/apiserver/apiextensions.go
  pkg/controlplane/apiserver/config.go
  pkg/kubelet/client/kubelet_client.go
  pkg/registry/apps/deployment/storage/storage.go
  pkg/registry/apps/replicaset/storage/storage.go
  pkg/registry/apps/statefulset/storage/storage.go
  pkg/registry/autoscaling/rest/storage_autoscaling.go
  pkg/registry/core/node/storage/storage.go
  pkg/registry/core/pod/rest/subresources.go
  pkg/registry/core/pod/strategy.go
  pkg/registry/policy/rest/storage_policy.go
  staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/etcd.go
  staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresourcedefinition/etcd.go
  staging/src/k8s.io/apiserver/pkg/endpoints/request/requestinfo.go
  staging/src/k8s.io/apiserver/pkg/registry/generic/registry/fleet.go
  staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go
  staging/src/k8s.io/apiserver/pkg/server/options/etcd.go
  staging/src/k8s.io/apiserver/pkg/server/storage/storage_factory.go
  staging/src/k8s.io/apiserver/pkg/storage/storagebackend/config.go
  staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
  staging/src/k8s.io/client-go/transport/round_trippers.go
Labels: lgtm, approved, size/L

#4 support exec with no proxy
  staging/src/k8s.io/apiserver/pkg/registry/generic/registry/fleet.go
Labels: kind/feature, lgtm, size/XS, approved

#5 bugfix: fix exec location when port is empty
  pkg/registry/core/pod/strategy.go
Labels: lgtm, size/XS, approved

#6 not supprt update/patch ingress object in the member clusters
  pkg/registry/networking/ingress/storage/storage.go
Labels: kind/feature, lgtm, size/S, approved
