Repository karmada-io/kubernetes, pull requests merged in 2024-01, with the labels that each got.

#8 fix: allow non system:master users to create/update rbac
  pkg/registry/rbac/clusterrole/policybased/storage.go
  pkg/registry/rbac/clusterrolebinding/policybased/storage.go
  pkg/registry/rbac/escalation_check.go
  pkg/registry/rbac/helpers.go
  pkg/registry/rbac/role/policybased/storage.go
  pkg/registry/rbac/rolebinding/policybased/storage.go
Labels: lgtm, approved, size/L

#9 Modify the content returned by the list interface
  staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go
Labels: kind/feature, lgtm, size/S, approved

#10 Support getting all resource through labelSelector with list/watch interface
  staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go
Labels: kind/feature, lgtm, size/M, approved
